language: ruby
rvm: 2.3.5
before_install:
- cd $TRAVIS_BUILD_DIR
- gem update bundler
install: bundle install --jobs 4
cache:
  directories:
  - vendor/bundle
before_script:
- unset RACK_ENV
script: bundle exec rspec
